name: Python Script Workflow

on:
  # Triggers the workflow at 14:00 GMT on every day-of-week from Monday through Friday.
  schedule:
    - cron: "0 14 * * 1-5"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3 # Checkout the repository content to GitHub runner.

      - name: Setup Python Version
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.2

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "requirements.txt"

      - name: Execute Python script # Run the app.py
        env:
          IMAP: ${{ secrets.IMAP }}
          MAIL: ${{ secrets.MAIL }}
          PASS: ${{ secrets.PASS }}
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}

        run: python app.py
